interface ReportData {
  peakRisk: string;
  scanCount: number;
  blockCount: number;
  capturedStream: Array<{ key: string; timestamp: number }>;
  reconstructedText: string;
}

export function generateReport(data: ReportData) {
  const reportContent = `
KEYLOGGER AWARENESS TOOL - SIMULATION REPORT
Generated: ${new Date().toLocaleString()}

═══════════════════════════════════════════════════════════════

DISCLAIMER
This report is generated from an educational simulation. No real
keylogging occurred. All data was captured only from the controlled
demo input box and was never transmitted to any external server.

═══════════════════════════════════════════════════════════════

SIMULATION SUMMARY

Peak Risk Level: ${data.peakRisk}
Total Scans Performed: ${data.scanCount}
Auto-Block Activations: ${data.blockCount}
Total Keystrokes Captured: ${data.capturedStream.length}

═══════════════════════════════════════════════════════════════

RECONSTRUCTED TEXT

${data.reconstructedText || 'No data captured yet'}

═══════════════════════════════════════════════════════════════

PREVENTION TIPS

1. Use Reputable Antivirus Software
   - Keep your antivirus updated
   - Enable real-time protection
   - Perform regular system scans

2. Practice Safe Browsing
   - Avoid suspicious websites
   - Don't download files from untrusted sources
   - Be cautious with email attachments

3. Use Strong Authentication
   - Enable two-factor authentication (2FA)
   - Use unique passwords for each account
   - Consider using a password manager

4. Keep Software Updated
   - Install security patches promptly
   - Enable automatic updates
   - Update all applications, not just OS

5. Be Aware of Physical Security
   - Don't leave devices unattended
   - Check for hardware keyloggers on public computers
   - Use privacy screens in public spaces

6. Monitor System Behavior
   - Watch for unusual system slowdowns
   - Check for unexpected network activity
   - Review installed programs regularly

7. Use Virtual Keyboards for Sensitive Data
   - Consider on-screen keyboards for passwords
   - Use biometric authentication when available

8. Educate Yourself
   - Stay informed about cybersecurity threats
   - Learn to recognize phishing attempts
   - Understand social engineering tactics

═══════════════════════════════════════════════════════════════

ADDITIONAL RESOURCES

- National Cyber Security Centre (NCSC)
- CISA Cybersecurity Tips
- Stay Safe Online
- Your organization's IT security team

═══════════════════════════════════════════════════════════════

This simulation was created for educational purposes only.
For questions about real cybersecurity threats, consult with
qualified security professionals.

Report generated by Keylogger Awareness Tool
  `;

  // Create blob and download
  const blob = new Blob([reportContent], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `keylogger-awareness-report-${Date.now()}.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
